#!/usr/bin/env bash
# Script that displays numbers from 1 to 100.FizzBuzz if multiple 3 and 5.Fizz if multiple of 3. Buzz if multiple of 5.

for i in {1..100}
do
    if [ $((i % 5)) -eq 0 -a $((i % 3)) -eq 0 ]
    then
	echo "FizzBuzz"
    elif [ $((i % 5)) -eq 0 ]
    then
	echo "Buzz"
    elif [ $((i % 3)) -eq 0 ]
    then
	echo "Fizz"
    else
	echo "$i"
    fi
done
