#!/usr/bin/env bash
# Bash script that displays the content of the file /etc/passwd.only username,user id and Home directory path for the user

while IFS= read -r line
do
    echo "$line" | cut -f 1,3,6 -d ':'
done < "/etc/passwd"
