#!/usr/bin/env bash
# Script loops from 1 to 10.bad luck for 4th.good luck for 8th.Best School for others.
c=1
while [ $c -le 10 ]
do 
     if [ "$c" -eq 4 ]
     then 
          echo "bad luck"
     elif [ "$c" -eq 8 ]
     then
           echo "good luck"
     else echo "Best School"
     fi 
     ((c++))
done
