#!/usr/bin/env bash
# Write a Bash script that displays numbers from 1 to 20 and:4 and bad luck from China,9 and bad luch from Japan,17 and bad luck from Italy.

c=1
while [ $c -le 20 ]
do
    echo "$c"
    case "${c}"
    in
        4) echo "bad luck from China";;
	9) echo "bad luck from Japan";;
	17) echo "bad luck from Italy";;
    esac
    ((c++))
done
