#!/usr/bin/env bash
# Write a Bash script that displays the time for 12 hours and 59 minutes:display hours from 0 to 12. display minutes from 1 to 59. Using while.

h=0
m=1
while [ $h -le 12 ]
do
    m=1
    echo "Hour: $h"
    while [ $m -lt 60 ]
    do
	echo $m
	((m++))
    done
    ((h++))
done
