#!/usr/bin/env bash
# Creates the file /var/run/myscript.pid containing its PID

rmfile_n_exit()
{
    rm -f /var/run/holbertonscript.pid;
    exit
}
trap "echo 'Y U no love me?!'" SIGINT
trap "echo 'I hate the kill command'; rmfile_n_exit" SIGTERM
trap "echo 'I hate the kill command'; rmfile_n_exit" SIGQUIT


echo $$ >> /var/run/holbertonscript.pid
while (true)
do
    echo 'To infinity and beyond'
    sleep 2
done
